# Generated by Django 4.2.2 on 2023-07-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('complite', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
