# Generated by Django 4.2.2 on 2023-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
