# Generated by Django 4.2.1 on 2023-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_works_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='complite',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
