# Generated by Django 4.2.1 on 2023-06-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_login_work_color_work_complite_work_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='color',
        ),
    ]
