# Generated by Django 4.2.1 on 2023-06-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_work_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
