# Generated by Django 4.2.1 on 2023-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_work_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
