# Generated by Django 4.2.1 on 2023-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
