# Generated by Django 4.2.1 on 2023-06-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='works',
            new_name='work',
        ),
    ]
